### ISSUE TITLE
Delete the uploaded image after processing

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#102]
The uploaded images are currently being saved in test_images folder which is mentioned in .gitignore, you are supposed to run a bash script(.sh) to delete the uploaded image after processing.

Hint : Use `rm -f test_images/fileUploadPath` command to delete that image.

**Comment by abhushanaj** [comment]
May I Sir??

**Comment by tanishq9** [comment]
Sure, now you can refer the link that I shared with you on slack.

**Comment by abhushanaj** [comment]
> Sure, now you can refer the link that I shared with you on slack.

Okay Sure! Thanks
