### ISSUE TITLE
Avoid Request Timeout [DEPLOYMENT ISSUE]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#106]
If the response time exceeds 30 seconds then output a dummy json (eg. potato healthy)

Observe the error logs : (the output comes after >30 seconds so no response is send even though we have predicted the output just 2-3 seconds after taking 30 seconds)
![Screenshot (300)](https://user-images.githubusercontent.com/35667308/79371373-e8ae7200-7f71-11ea-8d50-b9e9aaced771.png)

Although in some cases, it works when obviously the time taken is less than 30 seconds, as we can see in the image below, the response time taken was 25.9 seconds and 29.5 seconds for 2 requests that we send. 

![Screenshot (301)](https://user-images.githubusercontent.com/35667308/79372909-bdc51d80-7f73-11ea-9031-fa252e2d7bf6.png)

**Comment by abhushanaj** [comment]
Sir May I??

**Comment by tanishq9** [comment]
Yes, assigning you.
