### ISSUE TITLE
List all the crop leaf disease categories in text file

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#11]
Use the data modeling repository to get these categories, these values are needed because we will have to send the result to the user based on them.

**Comment by AdityaSingh17** [comment]
I would like to take this up!

**Comment by tanishq9** [comment]
Sure, assigning it to you.

**Comment by AdityaSingh17** [comment]
@tanishq9 are you interested in the code as well or just the .txt file will do?

**Comment by tanishq9** [comment]
No, code is not needed. Only the names of all categories of the crop disease in .txt file.
