### ISSUE TITLE
API TESTING [POSTMAN] [OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#114]
Use Postman to send a POST request at `http://crop-leaf.herokuapp.com/file_upload` and add your screenshot in `api_testing` folder. 

Reference link : https://stackoverflow.com/questions/39037049/how-to-upload-a-file-and-json-data-in-postman

Sample screenshot : 
![Screenshot (308)](https://user-images.githubusercontent.com/35667308/79638237-44f7d880-81a2-11ea-8848-0ef3cf02f810.png)

**Comment by akt114** [comment]
Can I still work in this issue?

**Comment by tanishq9** [comment]
Yes, you can @akt114

**Comment by akt114** [comment]
> Yes, you can @akt114

Cool, but what file do I need to POST? @tanishq9

**Comment by tanishq9** [comment]
@akt114 leaf image
