### ISSUE TITLE
REQUEST TIMEOUT [DEPLOY ISSUE : H12 ERR HEROKU]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#123]
Current logic to avoid timeout failing.

Attaching screenshot for the issue :

![Screenshot (310)](https://user-images.githubusercontent.com/35667308/79642138-7def7780-81b9-11ea-820f-846c3b2df410.png)

**Comment by abhushanaj** [comment]
Can I try?

**Comment by tanishq9** [comment]
Sure.

**Comment by abhushanaj** [comment]
> Sure.

Sir, this one is the exception condition only correct?

**Comment by tanishq9** [comment]
No, this is an error not an exception, also the default category is not being returned.
