### ISSUE TITLE
Lacking License

### ISSUE THREAD

**Issue by Souvikns** [CropAi/Backend#132]

**Comment by Souvikns** [comment]
The license tag in the readme file is showing not specified. When I checked I found the repo doesn't have a license yet. I thought of adding a license and then creating a pull request but then I figured that I should the maintainer first.

**Comment by tanishq9** [comment]
@Souvikns you can make a PR for it, I will review it.

**Comment by Souvikns** [comment]
which license should I add

**Comment by tanishq9** [comment]
What all options do we have ?

**Comment by Souvikns** [comment]
I guess MIT Apache 2.0 and all the free opensource license GitHub gives us

**Comment by tanishq9** [comment]
Let's go for MIT License as it lets people do almost anything they want with the project, like making and distributing closed source versions.

**Comment by Souvikns** [comment]
Ok I am putting it

**Comment by Souvikns** [comment]
I have created a PR
