### ISSUE TITLE
Create a public folder, add index.html file and form to input file 

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#14]
the form will input file and send it to backend for crop disease detection, styling html is not compulsory, separate issue will be created for it

**Comment by abhushanaj** [comment]
@tanishq9  Sir May I work on this. ? I have been waiting for this project to start backend and FE work for long time.  I won't claim other issue after this, since I know others have to work as well on it. :)

**Comment by abhu-A-J** [comment]
> @tanishq9 Sir May I work on this. ? I have been waiting for this project to start backend and FE work for long time.

I won't claim any other issue after this ! :)

**Comment by tanishq9** [comment]
Yes, we will working on backend for this week. You can claim other issues as well, I can assign a single issue to multiple interested participants, so whosoever is interested will definitely get a chance.
