### ISSUE TITLE
Add body parser and static middleware by Express in server.js

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#17]
Since, we are passing a form from frontend so we have to parse incoming request bodies in a middleware. Also, to serve static files such as images, CSS files, and JavaScript files, use the express.static built-in middleware function in Express.

Incorporate these changes in server.js.

**Comment by abhushanaj** [comment]
@tanishq9 Sir May I work on this?? Thank you!

**Comment by tanishq9** [comment]
Yes, but first make changes to the previous PR. At a time, a participant can work on only one issue.
