### ISSUE TITLE
Make a dummy python file and call it inside server.js when file submit button is clicked

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#18]
We would be calling Python script from a Node child process, using python-shell package. The dummy .py file should print("script called"), this .py script will be called on post request at route '/file_upload'. To know more about integrating node with python, read this : 

https://medium.com/@HolmesLaurence/integrating-node-and-python-6b8454bfc272

It is mentioned in this blog, how to create node child process using python-shell package, go through this, we will be using the same method as 'Version 2: calling Python script from a Node child process, using python-shell package' mentioned in the above blog.

**Comment by abhushanaj** [comment]
@tanishq9 Sir, May I work on this? This looks like a new concept

**Comment by tanishq9** [comment]
Yes, I am assigning it you. All the best.
