### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#33]
List the basic to advanced git concepts and commands that a participant would require to contribute to any particular repository's codebase, also telling about the best practices for contributing.

Since, every contributor for this repository will have to go through it, so try to make it as intuitive, detailed and informative as possible. 

Should preferably be a markdown(.md) file.

**Comment by abhushanaj** [comment]
@tanishq9  May I try this Sir?

**Comment by tanishq9** [comment]
Assigning it to you.

**Comment by Adyasha8105** [comment]
@tanishq9  can I?

**Comment by tanishq9** [comment]
Yes, assigning you as well.

**Comment by tanishq9** [comment]
You both can take your time and submit a PR for this issue till tomorrow 1pm.
