### ISSUE TITLE
show the leaf image selected by user below the file upload form. [HTML+CSS]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#68]
![addimagediv](https://user-images.githubusercontent.com/35667308/78137706-69824f80-7443-11ea-8159-91d590070598.gif)
Any more modifications to UI are also welcome.

**Comment by abhishekgupta368** [comment]
We can add:
1) Navigation Bar
2) Make the box corner round
3) can have so dynamic background

**Comment by abhishekgupta368** [comment]
Can also add feed box, Where we can show news and update regarding agriculture technique

**Comment by abhushanaj** [comment]
@tanishq9 Sir  I want to try this.

**Comment by tanishq9** [comment]
assigning it to you, please don't modify the file upload form, just style it more because the html part needs no changes.

**Comment by tanishq9** [comment]
@abhu-A-J another issue opened up, you want that ?

**Comment by abhushanaj** [comment]
> We can add:
> 
> 1. Navigation Bar
> 2. Make the box corner round
> 3. can have so dynamic background

I think this should be in FE repo?? and not backend.??

**Comment by abhishekgupta368** [comment]
where is front-end

**Comment by tanishq9** [comment]
Yes, the main purpose of this repo is to get the API working but still if he wants to style it more, let it be. Frontend will consider all these designs versions.
