### ISSUE TITLE
use formidable module for parsing form data, i.e file uploads, save this file in the backend and pass this as argument to dummy.py. [JS+PYTHON]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#69]
Refer this to know how to use formidable : https://www.npmjs.com/package/formidable

Also, the dummy.py script should return the first 5 characters of the file name, why ? Just to check whether we are able to correctly send the file path from the child process that we created in '/file_upload' route 

Make sure the image file is being saved in the backend, this image will be required by our python script later on.

**Comment by abhishekgupta368** [comment]
what we need to do, I don't understand?

**Comment by abhushanaj** [comment]
@tanishq9  Sir, thank you for creating such awesome issues. I want to try this.

**Comment by tanishq9** [comment]
Sure, let me explain this issue, the form that will be used to upload leaf image will be sent to the backend post route of '/file_upload' for processing. Assigning it @abhu-A-J
