### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by Aju100** [CropAi/Backend#7]

**Comment by Aju100** [comment]
tanishq9  can you assigned me this ,i would be happy to contribute on the project ?

**Comment by preeti13456** [comment]
Interested

**Comment by ujjawal01** [comment]
can i work on this issue? @gshanbhag525  @tanishq9  @Aju100

**Comment by suchi12j** [comment]
Can I work on this?

**Comment by Riyagoel2** [comment]
I also want to work on it
