### ISSUE TITLE
use all the files in leaf-disease folder and convert each of them to JSON. [JSON+FORMATTING]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#70]
The reason is that the python script will send us the label of the leaf disease. According to that, we will send the JSON as output, it is a part of file_upload post route API. Make a separate data.js file and write all diseases JSON there. Refer this screenshot for details.

![output_image](https://user-images.githubusercontent.com/35667308/78139246-d0086d00-7445-11ea-897f-2426d11b9596.png)

Here, op is the output JSON object. You can rename it to output.

**Comment by abhushanaj** [comment]
@tanishq9 Sir Can I take this as well. No one seems to be assigned on this yet!

**Comment by tanishq9** [comment]
Sure. Its a very monotonous work, you have copy from text files and write it in JSON format, you might get bored. So, I would strongly recommend listening to some music while doing this 😆 
Also, I assume, since you have worked on file_upload POST route and what it returns, you can modify that to return the required JSON based on the output(predicted) label category.

**Comment by abhushanaj** [comment]
> Sure. Its a very monotonous work, you have copy from text files and write it in JSON format, you might get bored. So, I would strongly recommend listening to some music while doing this 😆
> Also, I assume, since you have worked on file_upload POST route and what it returns, you can modify that to return the required JSON based on the output(predicted) label category.

Okay! I'll do the same! :)
