### ISSUE TITLE
add label_image.py script which was made/issue in data modeling repo. [Python+Tensorflow]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#71]
this label_image.py script is used to predict the leaf image's label

**Comment by AdityaSingh17** [comment]
Just a query, do we have to just copy the same file and add it here or make the file from scratch again?
In either of the cases, I would like to work on this issue.

**Comment by tanishq9** [comment]
Yes, the code won't change. Labeling it as hard, because I expect it to work correctly with nodejs backend as well. Many of the participants might have to pip install all these dependencies, and will face issue. I want to see screenshots of the script working when it is called inside a child process of file_upload POST route.

**Comment by AdityaSingh17** [comment]
@tanishq9 I would like to try this out. Give me a day to try it, if I am unable to produce results you may assign the next willing participant.

**Comment by tanishq9** [comment]
@AdityaSingh17 you want to close this issue ?

**Comment by AdityaSingh17** [comment]
@tanishq9 Yes!

**Comment by tanishq9** [comment]
Ok, assigning you.

**Comment by tanishq9** [comment]
@AdityaSingh17 how much time will it take ? Is it possible tomorrow before 1 pm ?
