### ISSUE TITLE
google drive link of the h5 model file

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#72]
make a text file with link of pre-trained model for classifying leaf disease label

**Comment by AdityaSingh17** [comment]
I would like to work on this issue!

**Comment by tanishq9** [comment]
You have the most updated h5 link ?

**Comment by AdityaSingh17** [comment]
Yes, @gshanbhag525 had sent me the link to be used for prediction function in label_images.py file.

**Comment by tanishq9** [comment]
okay, then make a text file for that link, make sure link is not broken and has access to everyone. Also, make changes to readme by specifying the gdrive link there as well. Assigning you.

**Comment by AdityaSingh17** [comment]
Where should I text you? @tanishq9

**Comment by tanishq9** [comment]
I have written make a text file not text me.

**Comment by tanishq9** [comment]
Assigning it to you.

**Comment by tanishq9** [comment]
I have assigned it to you, you can start working on it.
