### ISSUE TITLE
create license

### ISSUE THREAD

**Issue by Aju100** [CropAi/Backend#8]

**Comment by Aju100** [comment]
gshanbhag525 hello sir, which type of license can we create for assigning this issue ?

**Comment by imrishabh18** [comment]
Can i work on this ?

**Comment by preeti13456** [comment]
Interested

**Comment by ujjawal01** [comment]
i want to work on this issue, can i start?
@gshanbhag525

**Comment by suchi12j** [comment]
What exactly we have to do on this?
