### ISSUE TITLE
Use the model api deployed on : (http://cropaitest.pythonanywhere.com/upload) to get the label of image file uploaded by user

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#84]
The image from backend has to be send in base64 encoded form. Don't forget to go through the model api : https://github.com/CropAi/Data-Modeling/blob/master/flask_api_deployed/cropaiflask.py

You might get 414 and 500 errors, try to figure out how to correct them.

**Comment by abhushanaj** [comment]
I'd like to try this Sir?

**Comment by tanishq9** [comment]
assigning you

**Comment by abhishekgupta368** [comment]
this error is coming due to slow response time of the prediction and exceeding 30 sec in giving result.

**Comment by tanishq9** [comment]
In this case, you will have to set the connect, read, write timeouts for the request object, which depends upon on what API you are using to send these http requests.
