### ISSUE TITLE
Share screenshots of successful working of backend [LOCAL SERVER SETUP] [OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#85]
[Video Link for Backend Working](https://www.youtube.com/watch?v=BijRVVunqME) [Watch this to know better]

This issue is open for all participants. (share screenshots of your backend working) 

Follow the given instructions to update your backend repository :

1. Firstly and most importantly, you need to have `node` installed in your system, so please go through the [README.md file](https://github.com/CropAi/Backend/blob/master/README.md) then only you can continue with the below points.
2. Update your local repository first (git pull upstream master), considering you have named this remote 'upstream'.
3. Now, do `npm install` to install the required npm modules and `npm install python-shell` to install node python shell package.
4. Go to `localhost:3000` and select leaf image to see its category.
5. Incase you get any `ModuleNotFoundError` due to imports required in python script then install those module, eg : `pip3 install tensorflow` will be used to install tensorflow for python 3.x version on your system. You might get other errors as well, do use google and stackoverflow for them, most of them are common errors. If you are still stuck, feel free to pm me on slack.
5. Once done, add screenshot of your `backend logs` to the `screenshots_folder`.

PS : Since, the h5 file size that will get downloaded to your local system will be >100mb, so don't push that file when trying to pull any request for merging, your local cloned repository will otherwise get some irreversible errors. The reason to be cautious of not pushing file>100mb is because maximum project size on github is 100mb, so that is why you will face error when pushing.

PPS : It will take around 15 seconds to get output from the python script, since the model has got quite a complex architecture.

**Comment by shreyakapoor08** [comment]
can I do this?

**Comment by tanishq9** [comment]
ok, make sure you have understood the issue clearly.

**Comment by abhishekgupta368** [comment]
I can do it, assign me, please

**Comment by abhishekgupta368** [comment]
I want to work, assign me please

**Comment by tanishq9** [comment]
It is assigned to everyone. I have written : OPEN FOR ALL in the issue name itself !

**Comment by Kuljeet-123** [comment]
@tanishq9 Can I do this??

**Comment by tanishq9** [comment]
@Kuljeet-123 , it's open for all !
