### ISSUE TITLE
Refactor 'file_upload' route code to send the JSON according to the predicted category

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#87]
Example if the output from python script is : 'Pepper__bell___Bacterial_spot', then use `data.js` to send the appropriate JSON as response.

**Comment by abhushanaj** [comment]
Sir may I?

**Comment by abhishekgupta368** [comment]
I can do it

**Comment by tanishq9** [comment]
sure, assigning it to you.

**Comment by tanishq9** [comment]
@abhishekgupta368 first complete the screenshot issue, you will get better insight into this issue then
