### ISSUE TITLE
Add icon logo for the website

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#89]
Inside the `<head>` tag add logo of website using the `<link>` tag. The logo is same as this organisation's github logo.

**Comment by abhushanaj** [comment]
May i?

**Comment by Adyasha8105** [comment]
may i?

**Comment by abhishekgupta368** [comment]
Can I do it?

**Comment by tanishq9** [comment]
@abhishekgupta368  assigning you, @abhu-A-J you may continue your work on last issue's PR.

**Comment by abhishekgupta368** [comment]
Where is the logo, can you please tell me?
