### ISSUE TITLE
Restructure output JSON

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Backend#92]
Currently, we have 3 keys in JSON for every 'leaf disease' which are : symptoms, treatment and recommended products, add one more key of name : 'category' which tells the leaf disease name.

**Comment by abhushanaj** [comment]
May I Sir. Also, should the name contain underscores ?? Or it should be grammatically correct like Tomato Septoria Leaf instead of Tomato_Septoria_Leaf?? Thank you!

**Comment by tanishq9** [comment]
yes assigning it to you, you can name it 'Tomato Septoria Leaf' instead of 'Tomato_Septoria_Leaf'.
